### PR TITLE
fix(binding-mqtt): fix sending plain value instead of content object

### LINKED ISSUE #979: Mqtt handleAction and handleWriteProperty do not work as expected
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-mqtt/src/mqtt-broker-server.ts#L269

https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-mqtt/src/mqtt-broker-server.ts#L303

The lines above send just a JSON object or string (in case of a parsing error for handleAction) to `handleInvokeAction` and `handleWriteProperty` function, where functions need a `Content` object instead. And with these non-Content values `InteractionOutput`s are created, after we make a call for `InteractionOutput`s value error occurs because `InteractionOutput`s content is not actually a content but JSON object or string.

I have seen that for other protocol bindings using forms' contentType, `Content` object is created: 
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-coap/src/coap-server.ts#L456-L460

Should we also apply same kind of logic here or should we follow some other method?

### PR DESCRIPTION
**Pull request by hasanheroglu**
Closes #979

### CODE REVIEW

**Comment by hasanheroglu** [comment]
Since segments indices are wrong, I could not add tests. If it is okay, I will add the tests with segment indices fix.

File: packages/binding-mqtt/src/mqtt-broker-server.ts [hunk 1]
```diff
@@ -300,7 +306,11 @@ export default class MqttBrokerServer implements ProtocolServer {
             };
 
             try {
-                thing.handleWriteProperty(segments[3], JSON.parse(payload.toString()), options);
+                thing.handleWriteProperty(
+                    segments[3],
+                    new Content(ContentSerdes.DEFAULT, Readable.from(payload.toString())),
```
Comment (danielpeintner) [inline packages/binding-mqtt/src/mqtt-broker-server.ts:311]: Question: Should it be 
new Content(ContentSerdes.DEFAULT, Readable.from(JSON.parse(payload.toString()))
as it used to be in 
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-mqtt/src/mqtt-broker-server.ts#L303

Please check.

**Comment by danielpeintner** [comment]
> Since segment indices are wrong, I could not add tests. If it is okay, I will add the tests with segment indices fix.

I think the fix is easy enough that tests can (and should) follow later.
@egekorkan @relu91

File: packages/binding-mqtt/src/mqtt-broker-server.ts (hunk 1 above)
Comment (danielpeintner) [reply packages/binding-mqtt/src/mqtt-broker-server.ts]: Note: this might need checks/tests especially with a variation of input: simple types (int, boolean, etc) vs composed types (like objects and arrays)

Comment (hasanheroglu) [reply packages/binding-mqtt/src/mqtt-broker-server.ts]: Checking now

Comment (hasanheroglu) [reply packages/binding-mqtt/src/mqtt-broker-server.ts:307]: Passing JSON object to `Readable.from` creates an issue except when JSON only a string, therefore it seems like we should not use `JSON.parse`.

Comment (danielpeintner) [reply packages/binding-mqtt/src/mqtt-broker-server.ts:307]: Thanks for checking 👍
We should add tests in follow-up PR for it.

**Comment by egekorkan** [comment]
We will definitely follow up with the tests since so many PRs are interlinked at the moment.

**Review by danielpeintner — APPROVED** [review]

**Review by relu91 — CHANGES_REQUESTED** [review]

File: packages/binding-mqtt/src/mqtt-broker-server.ts [hunk 2]
```diff
@@ -266,7 +268,7 @@ export default class MqttBrokerServer implements ProtocolServer {
         };
 
         thing
-            .handleInvokeAction(segments[3], value, options)
+            .handleInvokeAction(segments[3], new Content(ContentSerdes.DEFAULT, Readable.from(value)), options)
```
[the remark this answers is not in the document]
Comment (hasanheroglu) [reply packages/binding-mqtt/src/mqtt-broker-server.ts:271]: Should we also apply the same for handlePropertyWrite? In there we try to get contentType from `packet.properties` but not from the forms.

[the remark this answers is not in the document]
Comment (hasanheroglu) [reply packages/binding-mqtt/src/mqtt-broker-server.ts]: Fixed here: [c32b712](https://github.com/eclipse/thingweb.node-wot/pull/987/commits/c32b712a0009913f077994bba17ede76bac7017e)

**Review by relu91 — APPROVED** [review]
Thank you LGTM
